#include "Cercle.h"
#include <iostream>

using namespace std;

#define _USE_MATH_DEFINES
#include <math.h>

Cercle::Cercle()
{
    std::cout << "Constructeur de Cercle" << std::endl;
}

double Cercle::CalculerSurface(double diametre, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 begin
{
    Surface = M_PI * diametre;
    return Surface;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A begin
{
    Perimetre = (2 * (diametre / 2)) * M_PI;
    return Perimetre;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

