#include "FormesGeometriques.h"
#include <iostream>

using namespace std;

FormesGeometriques::FormesGeometriques()
{
    Surface = 0.0;
    Perimetre = 0.0;

    m_Surface = 0;
    m_Perimetre = 0;
    
    std::cout << "Constructeur de formes geometriques" << std::endl;
    std::cout << std::endl;
}

double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 begin
{
    return 0.0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D begin
{
    return Surface;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F begin
{
    return Perimetre;
}

// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
