#include "TriangleRectangle.h"
#include <iostream>

#define _USE_MATH_DEFINES
#include <math.h>
#include <cmath>

using namespace std;


TriangleRectangle::TriangleRectangle()
{
    std::cout << "Constructeur de TrangleRectangle" << std::endl;
}

double TriangleRectangle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D60 begin
{
    Surface = (base * hauteur) / 2;

    return Surface;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D64 begin
{
    double hipo = 0;
    
    hipo = sqrt((base * base) + (hauteur * hauteur));

    Perimetre = base + hauteur + hipo;

    return Perimetre;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
