#include "Utilisateur.h"
#include "TriangleRectangle.h"
#include "Rectangle.h"
#include "Cercle.h"
#include <iostream>


void Utilisateur::AfficherResultats()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 begin
{
    switch (m_CodeFormeChoisie)
    {
    case 0:
        std::cout << "Pour un triangle rectangle de base = " << m_x1 << " et hauteur = " << m_x2 << 
        " surface = " << myFormesGeometriques->GetSurface() << " Perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
        std::cout << std::endl;
        break;
    case 1:
        std::cout << "Pour un rectangle de largeur = " << m_x1 << " hauteur = " << m_x2 <<
        " surface = " << myFormesGeometriques->GetSurface() << " Perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
        std::cout << std::endl;
        break;
    case 2:
        std::cout << "Pour un cercle de diametre = " << m_x1 << 
        " surface = " << myFormesGeometriques->GetSurface() << " Perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
        std::cout << std::endl;
        break;
    default:
        break;
    }
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Utilisateur::ChoisirForme(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 begin
{
    m_CodeFormeChoisie = CodeForme;

    switch (m_CodeFormeChoisie)
    {
    case 0:
        myFormesGeometriques = new TriangleRectangle();
        break;
    case 1:
        myFormesGeometriques = new Rectangle();
        break;
    case 2:
        myFormesGeometriques = new Cercle();
        break;
    default:
        return 1;
        break;
    }
    return 0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::SaisirLesParametres()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 begin
{
    switch (m_CodeFormeChoisie)
    {
    case 0:
        std::cout << "Entrez la base du triangle = ";
        std::cin >> m_x1;
        std::cout << "Entrez l'hauteur du triangle  = ";
        std::cin >> m_x2;
        break;
    case 1:
        std::cout << "Entrez la largeur du rectangle :";
        std::cin >> m_x1;
        std::cout << "Entrez l'hauteur du rectangle :";
        std::cin >> m_x2;
        break;
    case 2:
        std::cout << "Entrez le diametre du cercle:";
        std::cin >> m_x1;
        m_x2 = 0;
        break;
    default:
        m_x1 = 0;
        m_x2 = 0;
        break;
    }
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::ExecuterLesCalculs()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 begin
{
    myFormesGeometriques->CalculerPerimetre(m_x1, m_x2);
    myFormesGeometriques->CalculerSurface(m_x1, m_x2);
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
